Store/Models/Features/Basket.cs
namespace Store.Models.Features;

public class Basket
{
    private List<BasketItem> _items = new List<BasketItem>();
    public void Add(Person p, int quantity)
    {
        var baskeyItem = _items.Where(c => c.person.Id == p.Id).FirstOrDefault();
        if (baskeyItem != null)
        {
            baskeyItem.Quantity += quantity;
        }
        else
        {
            _items.Add(new BasketItem
            {
                Quantity = quantity,
                person = p
            });
        }
    }

    public void Remove(Person p)
    {
        _items.RemoveAll(c => c.person.Id == p.Id);
    }

    public int TotalPrice() => _items.Sum(c => c.person.Id * c.Quantity);

    public void Clear() => _items.Clear();

    public IEnumerable<BasketItem> Items => Items;
}

public class BasketItem
{
    public int Id { get; set; }
    public Person person { get; set; }
    public int Quantity { get; set; }
}

        

Store/Models/Person.cs
namespace Store.Models
{
    public class Person
    {
        public int Id { get; set; }
        public string categoryCustomers { get; set; }
        public string? FirstName { get; set; }
        public string? LastName { get; set; }
    }
}

Store/Models/PersonDbContext.cs
using Microsoft.EntityFrameworkCore;

namespace Store.Models
{
    public class PersonDbContext : DbContext
    {
        public DbSet<Person> People { get; set; }
        public PersonDbContext(DbContextOptions options) : base(options)
        {
        }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<Person>().HasData(
                new Person
                {
                    Id = 1,
                    categoryCustomers = "Golden",
                    FirstName ="Yasin",
                    LastName="ValiPour"
                },
                new Person
                {
                    Id = 2,
                    categoryCustomers = "Golden",
                    FirstName = "Ali",
                    LastName = "Hafezi"
                },
                new Person
                {
                    Id = 3,
                    categoryCustomers = "Golden",
                    FirstName = "MohammadReza",
                    LastName = "Sohrablo"
                },
                new Person
                {
                    Id = 4,
                    categoryCustomers = "Golden",
                    FirstName = "Ali",
                    LastName = "Hasani"
                },
                new Person
                {
                    Id = 5,
                    categoryCustomers = "Bronze",
                    FirstName = "Radin",
                    LastName = "Mahfozian"
                },
                new Person
                {
                    Id = 6,
                    categoryCustomers = "Bronze",
                    FirstName = "Parsa",
                    LastName = "Mohammadi"
                },
                new Person
                {
                    Id = 7,
                    categoryCustomers = "Simple",
                    FirstName = "Parsa",
                    LastName = "Khezli"
                },
                new Person
                {
                    Id = 8,
                    categoryCustomers = "Simple",
                    FirstName = "Nima",
                    LastName = "tarhani"
                },
                new Person
                {
                    Id = 9,
                    categoryCustomers = "Simple",
                    FirstName = "Ali",
                    LastName = "Mashhadi"
                },
                new Person
                {
                    Id = 10,
                    categoryCustomers = "Simple",
                    FirstName = "Omid",
                    LastName = "Asadi"
                }
            );
            base.OnModelCreating(modelBuilder);
        }
    }
}

Store/Models/PersonListViewModel.cs
using Store.Pager;

namespace Store.Models
{
    public class PersonListViewModel
    {
        public PageData<Person>? data { get; set; }
        public string? CurrentCategory { get; set; }
    }
}

Store/Components/SideMenuNavBarViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using Store.Operation;

namespace Store.Components
{
    public class SideMenuNavBarViewComponent : ViewComponent
    {
        private readonly IPeopleReader peopleReader;
        public SideMenuNavBarViewComponent(IPeopleReader peopleReader)
        {
            this.peopleReader = peopleReader;
        }

        public IViewComponentResult Invoke()
        {
            var currentCategory = RouteData.Values["categoryCustomers"];
            ViewBag.Category = currentCategory;
            return View(peopleReader.GetAllCategory());
        }
    }
}

Store/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Store.Models;
using Store.Operation;

namespace Store.Controllers
{
    public class HomeController : Controller
    {
        private int PageSize = 1;
        private readonly IPeopleReader peopleReader;
        public HomeController(IPeopleReader peopleReader)
        {
            this.peopleReader = peopleReader;
        }
        public IActionResult Index(string categoryCustomers = "", int PageNumber=1)
        {
            var viewmodel = new PersonListViewModel
            {
                CurrentCategory = categoryCustomers,
                data = peopleReader.GetAll(PageNumber, PageSize, categoryCustomers)
            };
            return View(viewmodel);
        }
    }
}

Store/Views/Home/Index.cshtml
@using Store.Pager
@model PersonListViewModel
@{
    ViewBag.Title = "YOo YoO";
}


@foreach (var item in Model.data.Data)
{
    @Html.Partial("_ItemsSummery", item)
}

<div id="pager-bottom">
    <div class="btn-group m-1" page-model="Model.data.PageInfo" page-action="Index" page-classes-enabled="true" page-class="btn" page-class-normal="btn-success" page-class-selected="btn-success"></div>
</div>

Store/Views/Shared/Components/SideMenuNavBar/Default.cshtml
@model List<string>

<style>
    #active-btn:hover{
        color: #fff;
        background-color: #212529;
    }
</style>



<a asp-controller="Home"
   asp-action="Index"
   asp-route-categoryCustomers=""
   asp-route-PageNumber="1"
   class="btn btn-success">
    All
</a>

@foreach (var item in Model)
{
    <a 
        asp-controller="Home"
        asp-action="Index"
        asp-route-categoryCustomers="@item"
        asp-route-PageNumber="1"
        class="btn"
        id="active-btn"
    >
            @item
    </a>
}

Store/Views/Shared/_ItemsSummery.cshtml
@model Person

<div style="margin: 10rem 0 ">
    <h1><small>@Model.Id </small>-
        <strong>
            @Model.FirstName @Model.LastName
        </strong>
    </h1>
    <p>Category Customers : <strong>@Model.categoryCustomers</strong></p>
</div>

Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <link rel="stylesheet" href="~/lib/bootstrap/css/bootstrap.css" />
    <title>@ViewBag.Title</title>
   <style>
        #pager-bottom{
            display: flex;
            justify-content: space-evenly;
            margin-bottom: 2rem;
        }
        #sidebar{
            display: flex;
            justify-content: space-evenly;
            align-items: center;
            background-color: beige;
        }
        #container{
            background-color: #20c99721;
        }
   </style>
</head>
<body>
    <div class=row>
        <div id="sidebar" class="col-3 container ">
            <vc:side-menu-nav-bar></vc:side-menu-nav-bar>
        </div>
        <div id="container" class="col-9 container">
            @RenderBody()
        </div>
    </div>
</body>
</html>